### ISSUE TITLE
add a possibility seriesDataIndexBinding with dynamic columns

### ISSUE THREAD

**Issue by schose** [hman-78/visualization_toolbox#10]
Hi all,

I'm searching for a possibility to visualize | timechart command result tables. in my scenario i do not know before how many columns my result table will have. This depends from the searched data..
We would need something which is able to create multiple series data and take the name of the column and pass it as name in the series. 

It would be great to have an even more flexible option to seriesDataIndexBinding for this usecase. 

Cheers,

Andreas

**Comment by ghost** [comment]
Hello,

The requested feature has been implemented here - https://github.com/hman-78/visualization_toolbox/pull/52

Thank you for reporting it.
