### ISSUE TITLE
Correct extracted folder name

### ISSUE THREAD

**Issue by iotspelunker** [hman-78/visualization_toolbox#2]
Currently the tar.gz file will be extracted into a folder named "splunk-visualization-toolbox". Should be "visualization-toolbox".

Solution: fix in tar creation action in workflow

**Comment by schose** [comment]
i suggest to use the Foldername visualization_toolbox and also use this as package name and app.manifest file. "-" not seems to be a valid character.

https://docs.splunk.com/Documentation/Splunk/9.0.0/Admin/Appconf 
```
* id must be the same as the folder name in which your app lives in
  $SPLUNK_HOME/etc/apps.
* id must adhere to these cross-platform folder name restrictions:
  * must contain only letters, numbers, "." (dot), and "_" (underscore)
    characters.
  * must not end with a dot character.
  * must not be any of the following names: CON, PRN, AUX, NUL,
      COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9,
      LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9
```

**Comment by ghost** [comment]
This issue is now resolved as can be seen here - https://github.com/hman-78/visualization_toolbox/blob/main/.github/workflows/release_app.yml
