### ISSUE TITLE
Extraneous triggers stanza in the default/addon_builder.conf in the tgz for version 0.3.0 

### ISSUE THREAD

**Issue by barrettnet** [hman-78/visualization_toolbox#57]
The tgz for version 0.3.0 available from here (https://github.com/hman-78/visualization_toolbox/releases) and from SplunkBase (https://splunkbase.splunk.com/app/6675) contains a default/addon_builder.conf which contains a triggers stanza with about a dozen reload settings.  The triggers stanza is not valid for the addon_builder.conf and causes errors during start up.

The triggers stanza is not present in the current codebase (for a currently unreleased 0.3.1?)  Is 0.3.1 ready for publishing to SplunkBase?

**Comment by ghost** [comment]
Hi Chris! 

Indeed the reload settings have been updated to fix the possible errors during startup. Version 0.3.1 will be soon (I hope this week) ready for publishing to SplunkBase.

**Comment by ghost** [comment]
[Release v0.4.0](https://github.com/hman-78/visualization_toolbox/releases/tag/v0.4.0) has been published and the startup errors are now resolved.
